"""Add timestamps to Note

Revision ID: 5a9adcc10f69
Revises: cc3d442ee92d
Create Date: 2026-01-12 22:02:26.689918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9adcc10f69'
down_revision: Union[str, Sequence[str], None] = 'cc3d442ee92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('note', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'updated_at')
    op.drop_column('note', 'created_at')
    # ### end Alembic commands ###
