"""Add profile_image to User

Revision ID: cc3d442ee92d
Revises: ea62f2011903
Create Date: 2026-01-12 12:57:20.627121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc3d442ee92d'
down_revision: Union[str, Sequence[str], None] = 'ea62f2011903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###
